language: node_js
node_js:
  - 8.11.1

branches:
  only:
    - develop
    
before_script:
  - psql -c 'create database travis;' -U postgres

env:
    - SECRET_TOKEN=abcxyz
    
script:
  - npm test
  
after_success: npm run coverage