
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_UNSUCCESSFUL = 'LOGIN_UNSUCCESSFUL';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL ';
export const SIGNUP_UNSUCCESSFUL = 'SIGNUP_UNSUCCESSFUL';
export const SIGNUP_VALIDATION_ERROR = 'SIGNUP_VALIDATION_ERROR';